/**
 * Almacén de intercambios por internet.
 * Persistente en Supabase (producción y desarrollo). // [MODIFICADO]
 */

export type TradeStatus = "pending" | "accepted" | "cancelled"

export interface Trade {
  id: string
  fromCode: string
  toCode: string
  cardId: string
  status: TradeStatus
  createdAt: string
}

import { supabase } from "@/lib/supabase-client" // [MODIFICADO]

function generateId(): string { // [MODIFICADO]
  return `trade-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`
}

export async function createTrade(fromCode: string, toCode: string, cardId: string): Promise<Trade> { // [MODIFICADO]
  const id = generateId() // [MODIFICADO]
  const createdAt = new Date().toISOString() // [MODIFICADO]
  const { data, error } = await supabase // [MODIFICADO]
    .from("intercambios_internet") // [MODIFICADO]
    .insert({ // [MODIFICADO]
      id, // [MODIFICADO]
      from_code: fromCode, // [MODIFICADO]
      to_code: toCode, // [MODIFICADO]
      card_id: cardId, // [MODIFICADO]
      status: "pending", // [MODIFICADO]
      created_at: createdAt, // [MODIFICADO]
    }) // [MODIFICADO]
    .select("id,from_code,to_code,card_id,status,created_at") // [MODIFICADO]
    .single() // [MODIFICADO]
  if (error || !data) { // [MODIFICADO]
    throw new Error(error?.message ?? "No se pudo crear el intercambio") // [MODIFICADO]
  } // [MODIFICADO]
  return { // [MODIFICADO]
    id: data.id, // [MODIFICADO]
    fromCode: data.from_code, // [MODIFICADO]
    toCode: data.to_code, // [MODIFICADO]
    cardId: data.card_id, // [MODIFICADO]
    status: data.status as TradeStatus, // [MODIFICADO]
    createdAt: new Date(data.created_at).toISOString(), // [MODIFICADO]
  } // [MODIFICADO]
} // [MODIFICADO]

export async function getTradesByToCode(toCode: string, status?: TradeStatus): Promise<Trade[]> { // [MODIFICADO]
  let q = supabase // [MODIFICADO]
    .from("intercambios_internet") // [MODIFICADO]
    .select("id,from_code,to_code,card_id,status,created_at") // [MODIFICADO]
    .eq("to_code", toCode) // [MODIFICADO]
    .order("created_at", { ascending: false }) // [MODIFICADO]
  if (status !== undefined) { // [MODIFICADO]
    q = q.eq("status", status) // [MODIFICADO]
  } // [MODIFICADO]
  const { data, error } = await q // [MODIFICADO]
  if (error || !data) { // [MODIFICADO]
    return [] // [MODIFICADO]
  } // [MODIFICADO]
  return data.map((row) => ({ // [MODIFICADO]
    id: row.id, // [MODIFICADO]
    fromCode: row.from_code, // [MODIFICADO]
    toCode: row.to_code, // [MODIFICADO]
    cardId: row.card_id, // [MODIFICADO]
    status: row.status as TradeStatus, // [MODIFICADO]
    createdAt: new Date(row.created_at).toISOString(), // [MODIFICADO]
  })) // [MODIFICADO]
} // [MODIFICADO]

export async function getTradesByFromCode(fromCode: string): Promise<Trade[]> { // [MODIFICADO]
  const { data, error } = await supabase // [MODIFICADO]
    .from("intercambios_internet") // [MODIFICADO]
    .select("id,from_code,to_code,card_id,status,created_at") // [MODIFICADO]
    .eq("from_code", fromCode) // [MODIFICADO]
    .order("created_at", { ascending: false }) // [MODIFICADO]
  if (error || !data) { // [MODIFICADO]
    return [] // [MODIFICADO]
  } // [MODIFICADO]
  return data.map((row) => ({ // [MODIFICADO]
    id: row.id, // [MODIFICADO]
    fromCode: row.from_code, // [MODIFICADO]
    toCode: row.to_code, // [MODIFICADO]
    cardId: row.card_id, // [MODIFICADO]
    status: row.status as TradeStatus, // [MODIFICADO]
    createdAt: new Date(row.created_at).toISOString(), // [MODIFICADO]
  })) // [MODIFICADO]
} // [MODIFICADO]

export async function getTradeById(id: string): Promise<Trade | undefined> { // [MODIFICADO]
  const { data, error } = await supabase // [MODIFICADO]
    .from("intercambios_internet") // [MODIFICADO]
    .select("id,from_code,to_code,card_id,status,created_at") // [MODIFICADO]
    .eq("id", id) // [MODIFICADO]
    .maybeSingle() // [MODIFICADO]
  if (error || !data) { // [MODIFICADO]
    return undefined // [MODIFICADO]
  } // [MODIFICADO]
  return { // [MODIFICADO]
    id: data.id, // [MODIFICADO]
    fromCode: data.from_code, // [MODIFICADO]
    toCode: data.to_code, // [MODIFICADO]
    cardId: data.card_id, // [MODIFICADO]
    status: data.status as TradeStatus, // [MODIFICADO]
    createdAt: new Date(data.created_at).toISOString(), // [MODIFICADO]
  } // [MODIFICADO]
} // [MODIFICADO]

export async function acceptTrade(id: string, toCode: string): Promise<Trade | null> { // [MODIFICADO]
  const { data, error } = await supabase // [MODIFICADO]
    .from("intercambios_internet") // [MODIFICADO]
    .update({ status: "accepted", accepted_at: new Date().toISOString() }) // [MODIFICADO]
    .eq("id", id) // [MODIFICADO]
    .eq("to_code", toCode) // [MODIFICADO]
    .eq("status", "pending") // [MODIFICADO]
    .select("id,from_code,to_code,card_id,status,created_at") // [MODIFICADO]
    .maybeSingle() // [MODIFICADO]
  if (error || !data) { // [MODIFICADO]
    return null // [MODIFICADO]
  } // [MODIFICADO]
  return { // [MODIFICADO]
    id: data.id, // [MODIFICADO]
    fromCode: data.from_code, // [MODIFICADO]
    toCode: data.to_code, // [MODIFICADO]
    cardId: data.card_id, // [MODIFICADO]
    status: data.status as TradeStatus, // [MODIFICADO]
    createdAt: new Date(data.created_at).toISOString(), // [MODIFICADO]
  } // [MODIFICADO]
} // [MODIFICADO]
