import { supabase } from "@/lib/supabase-client" // [MODIFICADO]

export interface UsuarioRow { // [MODIFICADO]
  id: number // [MODIFICADO]
  device_id: string | null // [MODIFICADO]
  nombre: string | null // [MODIFICADO]
  codigo_amigo: string | null // [MODIFICADO]
  foto_perfil: string | null // [MODIFICADO]
} // [MODIFICADO]

export async function getUsuarioByAuthUserId(authUserId: string): Promise<UsuarioRow | null> { // [MODIFICADO]
  try { // [MODIFICADO]
    const { data, error } = await supabase // [MODIFICADO]
      .from("usuarios") // [MODIFICADO]
      .select("*") // [MODIFICADO]
      .eq("auth_user_id", authUserId) // [MODIFICADO]
      .order("id", { ascending: true }) // [MODIFICADO]
      .limit(1) // [MODIFICADO]
      .maybeSingle() // [MODIFICADO]

    if (error) { // [MODIFICADO]
      console.error("Error seleccionando usuario por auth_user_id:", error) // [MODIFICADO]
      return null // [MODIFICADO]
    } // [MODIFICADO]

    return (data as UsuarioRow) ?? null // [MODIFICADO]
  } catch (error) { // [MODIFICADO]
    console.error("Error inesperado en getUsuarioByAuthUserId:", error) // [MODIFICADO]
    return null // [MODIFICADO]
  } // [MODIFICADO]
} // [MODIFICADO]

export async function getOrCreateUsuarioByAuthUserId(authUserId: string, deviceId?: string): Promise<UsuarioRow | null> { // [MODIFICADO]
  try { // [MODIFICADO]
    const existing = await getUsuarioByAuthUserId(authUserId) // [MODIFICADO]
    if (existing) { // [MODIFICADO]
      if (!existing.codigo_amigo) { // [MODIFICADO]
        const codigo = `USER${existing.id}` // [MODIFICADO]
        const { data: updatedCode, error: updateCodeError } = await supabase // [MODIFICADO]
          .from("usuarios") // [MODIFICADO]
          .update({ codigo_amigo: codigo }) // [MODIFICADO]
          .eq("id", existing.id) // [MODIFICADO]
          .select("*") // [MODIFICADO]
          .single() // [MODIFICADO]
        if (!updateCodeError && updatedCode) { // [MODIFICADO]
          return updatedCode as UsuarioRow // [MODIFICADO]
        } // [MODIFICADO]
      } // [MODIFICADO]
      if (deviceId && !existing.device_id) { // [MODIFICADO]
        const { data: updated, error: updateError } = await supabase // [MODIFICADO]
          .from("usuarios") // [MODIFICADO]
          .update({ device_id: deviceId }) // [MODIFICADO]
          .eq("id", existing.id) // [MODIFICADO]
          .select("*") // [MODIFICADO]
          .single() // [MODIFICADO]
        if (updateError) { // [MODIFICADO]
          console.error("Error vinculando device_id al usuario:", updateError) // [MODIFICADO]
          return existing // [MODIFICADO]
        } // [MODIFICADO]
        return updated as UsuarioRow // [MODIFICADO]
      } // [MODIFICADO]
      return existing // [MODIFICADO]
    } // [MODIFICADO]

    const { data: inserted, error: insertError } = await supabase // [MODIFICADO]
      .from("usuarios") // [MODIFICADO]
      .insert({ auth_user_id: authUserId, device_id: deviceId ?? null }) // [MODIFICADO]
      .select("*") // [MODIFICADO]
      .single() // [MODIFICADO]

    if (insertError) { // [MODIFICADO]
      console.error("Error creando usuario por auth_user_id:", insertError) // [MODIFICADO]
      return null // [MODIFICADO]
    } // [MODIFICADO]

    if (inserted && !(inserted as UsuarioRow).codigo_amigo) { // [MODIFICADO]
      const codigo = `USER${(inserted as UsuarioRow).id}` // [MODIFICADO]
      const { data: updatedCode, error: updateCodeError } = await supabase // [MODIFICADO]
        .from("usuarios") // [MODIFICADO]
        .update({ codigo_amigo: codigo }) // [MODIFICADO]
        .eq("id", (inserted as UsuarioRow).id) // [MODIFICADO]
        .select("*") // [MODIFICADO]
        .single() // [MODIFICADO]
      if (!updateCodeError && updatedCode) { // [MODIFICADO]
        return updatedCode as UsuarioRow // [MODIFICADO]
      } // [MODIFICADO]
    } // [MODIFICADO]

    return inserted as UsuarioRow // [MODIFICADO]
  } catch (error) { // [MODIFICADO]
    console.error("Error inesperado en getOrCreateUsuarioByAuthUserId:", error) // [MODIFICADO]
    return null // [MODIFICADO]
  } // [MODIFICADO]
} // [MODIFICADO]

export async function getOrCreateUsuarioByDeviceId(deviceId: string): Promise<UsuarioRow | null> { // [MODIFICADO]
  try { // [MODIFICADO]
    const { data: existing, error: selectError } = await supabase // [MODIFICADO]
      .from("usuarios") // [MODIFICADO]
      .select("*") // [MODIFICADO]
      .eq("device_id", deviceId) // [MODIFICADO]
      .maybeSingle() // [MODIFICADO]

    if (selectError) { // [MODIFICADO]
      console.error("Error seleccionando usuario:", selectError) // [MODIFICADO]
      return null // [MODIFICADO]
    } // [MODIFICADO]

    if (existing) { // [MODIFICADO]
      return existing as UsuarioRow // [MODIFICADO]
    } // [MODIFICADO]

    const { data: inserted, error: insertError } = await supabase // [MODIFICADO]
      .from("usuarios") // [MODIFICADO]
      .insert({ device_id: deviceId }) // [MODIFICADO]
      .select("*") // [MODIFICADO]
      .single() // [MODIFICADO]

    if (insertError) { // [MODIFICADO]
      console.error("Error creando usuario:", insertError) // [MODIFICADO]
      return null // [MODIFICADO]
    } // [MODIFICADO]

    return inserted as UsuarioRow // [MODIFICADO]
  } catch (error) { // [MODIFICADO]
    console.error("Error inesperado en getOrCreateUsuarioByDeviceId:", error) // [MODIFICADO]
    return null // [MODIFICADO]
  } // [MODIFICADO]
} // [MODIFICADO]

