import { supabase } from "@/lib/supabase-client" // [MODIFICADO]

export interface UsuarioRow { // [MODIFICADO]
  id: number // [MODIFICADO]
  device_id: string | null // [MODIFICADO]
  nombre: string | null // [MODIFICADO]
  codigo_amigo: string | null // [MODIFICADO]
  foto_perfil: string | null // [MODIFICADO]
} // [MODIFICADO]

export async function getUsuarioByAuthUserId(authUserId: string): Promise<UsuarioRow | null> { // [MODIFICADO]
  try { // [MODIFICADO]
    const { data, error } = await supabase // [MODIFICADO]
      .from("usuarios") // [MODIFICADO]
      .select("*") // [MODIFICADO]
      .eq("auth_user_id", authUserId) // [MODIFICADO]
      .maybeSingle() // [MODIFICADO]

    if (error) { // [MODIFICADO]
      console.error("Error seleccionando usuario por auth_user_id:", error) // [MODIFICADO]
      return null // [MODIFICADO]
    } // [MODIFICADO]

    return (data as UsuarioRow) ?? null // [MODIFICADO]
  } catch (error) { // [MODIFICADO]
    console.error("Error inesperado en getUsuarioByAuthUserId:", error) // [MODIFICADO]
    return null // [MODIFICADO]
  } // [MODIFICADO]
} // [MODIFICADO]

export async function getOrCreateUsuarioByDeviceId(deviceId: string): Promise<UsuarioRow | null> { // [MODIFICADO]
  try { // [MODIFICADO]
    const { data: existing, error: selectError } = await supabase // [MODIFICADO]
      .from("usuarios") // [MODIFICADO]
      .select("*") // [MODIFICADO]
      .eq("device_id", deviceId) // [MODIFICADO]
      .maybeSingle() // [MODIFICADO]

    if (selectError) { // [MODIFICADO]
      console.error("Error seleccionando usuario:", selectError) // [MODIFICADO]
      return null // [MODIFICADO]
    } // [MODIFICADO]

    if (existing) { // [MODIFICADO]
      return existing as UsuarioRow // [MODIFICADO]
    } // [MODIFICADO]

    const { data: inserted, error: insertError } = await supabase // [MODIFICADO]
      .from("usuarios") // [MODIFICADO]
      .insert({ device_id: deviceId }) // [MODIFICADO]
      .select("*") // [MODIFICADO]
      .single() // [MODIFICADO]

    if (insertError) { // [MODIFICADO]
      console.error("Error creando usuario:", insertError) // [MODIFICADO]
      return null // [MODIFICADO]
    } // [MODIFICADO]

    return inserted as UsuarioRow // [MODIFICADO]
  } catch (error) { // [MODIFICADO]
    console.error("Error inesperado en getOrCreateUsuarioByDeviceId:", error) // [MODIFICADO]
    return null // [MODIFICADO]
  } // [MODIFICADO]
} // [MODIFICADO]

